version: '3.4'

services:
  db:
    container_name: mysql-server-in-docker
    image: alexfariakof/mysql-server-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-local
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "@master$"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    ports:
      - "3306:3306"
      - "3308:3308"